# Generated by Django 3.0.4 on 2020-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Electronics', 'Mobile'), ('Beauty', 'Lipstick'), ('Wooden', 'Wooden'), ('crockery', 'crockery'), ('cloth', 'cloth')], max_length=50, null=True),
        ),
    ]
