# Generated by Django 3.0.4 on 2020-06-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200625_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='receive_quantity',
            new_name='received_quantity',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
