# Generated by Django 3.0.4 on 2020-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200626_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='issue_to',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
