# Generated by Django 3.0.4 on 2020-07-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200712_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='phone_number',
        ),
    ]
